export const laboratoryTestLabels: Record<string, string> = {
  labConversationVisualizationTitle: 'Conversation visualization',
  labContextWindowTitle: 'Windowed context (experimental)',
  labContextWindowDescription: 'Experimental windowed context.',
  labContextWindowEnabled: 'Enable windowed context',
  labContextWindowEnabledDesc: 'Uses notes and on-demand history instead of summary compaction.',
  labPlanWorktreeTitle: 'Prompt-managed worktree',
  labPlanWorktreeDescription: 'Experimental Agent-managed Direct plan worktrees',
  labPlanWorktreeEnabled: 'Enable prompt-managed plan worktrees',
  labPlanWorktreeEnabledDesc: 'Disabled by default',
  labProjectBoardTitle: 'Project board',
  labProjectBoardDescription: 'Project board description',
  labProjectBoardEnabled: 'Enable project board',
  labPptTitle: 'PPT agent',
  labPptDescription: 'PPT tool description',
  labPptEnabled: 'Enable ppt_agent',
  labPptEnabledDesc: 'Enable description',
  labPptModelMode: 'Model policy',
  labPptModelModeDesc: 'Model policy description',
  labPptModelModeInherit: 'Follow main model',
  labPptModelModeFixed: 'Use fixed model',
  labPptModel: 'PPT model',
  labPptModelDesc: 'PPT model description',
  labPptProvider: 'PPT model provider',
  labPptReasoning: 'PPT reasoning effort',
  labPptReasoningDesc: 'Reasoning description',
  labPptReasoningInherit: 'Follow main reasoning',
  labPptFast: 'Codex Fast mode',
  labPptFastDesc: 'Fast description',
  labPptFastUnsupportedHint: 'Fast unsupported hint'
}
